[package]
name = "lean-matrix-cookbook"
version = "0.1"
lean_version = "leanprover-community/lean:3.51.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "ef95945cd48c932c9e034872bd25c3c220d9c946"}
