[package]
name = "lean-matrix-cookbook"
version = "0.1"
lean_version = "leanprover-community/lean:3.50.3"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "a2706b55e8d7f7e9b1f93143f0b88f2e34a11eea"}
